### ISSUE TITLE
Game crashes on opening mod's settings

### ISSUE THREAD

**Issue by ArcturusLight1** [Tre5et/audio-hotkeys#1]
Crashes when settings are viewed in-world or via mod menu.

> The game crashed whilst rendering screen
> Error: java.lang.NoSuchFieldError: field_2054
[crash-2023-01-12_18.11.08-client.txt](https://github.com/Tre5et/audio-hotkeys/files/10403030/crash-2023-01-12_18.11.08-client.txt)

**Comment by Tre5et** [comment]
Thanks for reporting this!

This seems to actually be an issue with VanillaConfig on 1.19.2 (fixed in the 1.19.3 releases).

Since I don't have the time to officially support older (sub-)versions, I won't make an official release for this though.
Because it was easy enough to track down however, I'll leave you a (mind you, largely untested) build of VanillaConfig here, that fixes this crash.

[vanillaconfig-1.2.2+1.19.x-crash-patch.zip](https://github.com/Tre5et/audio-hotkeys/files/10404208/vanillaconfig-1.2.2%2B1.19.x-crash-patch.zip)
